#pragma once

#include <tinyimageformat_base.h>
#include "base/base.h"

#define BIT( x ) 1 << x

typedef enum RendererAPI
{
	FT_RENDERER_API_VULKAN = 0,
	FT_RENDERER_API_D3D12  = 1,
	FT_RENDERER_API_METAL  = 2,
} RendererAPI;

typedef enum QueueType
{
	FT_QUEUE_TYPE_GRAPHICS = 0,
	FT_QUEUE_TYPE_COMPUTE  = 1,
	FT_QUEUE_TYPE_TRANSFER = 2,
	FT_QUEUE_TYPE_COUNT
} QueueType;

typedef enum Format
{
	FT_FORMAT_UNDEFINED             = TinyImageFormat_UNDEFINED,
	FT_FORMAT_R1_UNORM              = TinyImageFormat_R1_UNORM,
	FT_FORMAT_R2_UNORM              = TinyImageFormat_R2_UNORM,
	FT_FORMAT_R4_UNORM              = TinyImageFormat_R4_UNORM,
	FT_FORMAT_R4G4_UNORM            = TinyImageFormat_R4G4_UNORM,
	FT_FORMAT_G4R4_UNORM            = TinyImageFormat_G4R4_UNORM,
	FT_FORMAT_A8_UNORM              = TinyImageFormat_A8_UNORM,
	FT_FORMAT_R8_UNORM              = TinyImageFormat_R8_UNORM,
	FT_FORMAT_R8_SNORM              = TinyImageFormat_R8_SNORM,
	FT_FORMAT_R8_UINT               = TinyImageFormat_R8_UINT,
	FT_FORMAT_R8_SINT               = TinyImageFormat_R8_SINT,
	FT_FORMAT_R8_SRGB               = TinyImageFormat_R8_SRGB,
	FT_FORMAT_B2G3R3_UNORM          = TinyImageFormat_B2G3R3_UNORM,
	FT_FORMAT_R4G4B4A4_UNORM        = TinyImageFormat_R4G4B4A4_UNORM,
	FT_FORMAT_R4G4B4X4_UNORM        = TinyImageFormat_R4G4B4X4_UNORM,
	FT_FORMAT_B4G4R4A4_UNORM        = TinyImageFormat_B4G4R4A4_UNORM,
	FT_FORMAT_B4G4R4X4_UNORM        = TinyImageFormat_B4G4R4X4_UNORM,
	FT_FORMAT_A4R4G4B4_UNORM        = TinyImageFormat_A4R4G4B4_UNORM,
	FT_FORMAT_X4R4G4B4_UNORM        = TinyImageFormat_X4R4G4B4_UNORM,
	FT_FORMAT_A4B4G4R4_UNORM        = TinyImageFormat_A4B4G4R4_UNORM,
	FT_FORMAT_X4B4G4R4_UNORM        = TinyImageFormat_X4B4G4R4_UNORM,
	FT_FORMAT_R5G6B5_UNORM          = TinyImageFormat_R5G6B5_UNORM,
	FT_FORMAT_B5G6R5_UNORM          = TinyImageFormat_B5G6R5_UNORM,
	FT_FORMAT_R5G5B5A1_UNORM        = TinyImageFormat_R5G5B5A1_UNORM,
	FT_FORMAT_B5G5R5A1_UNORM        = TinyImageFormat_B5G5R5A1_UNORM,
	FT_FORMAT_A1B5G5R5_UNORM        = TinyImageFormat_A1B5G5R5_UNORM,
	FT_FORMAT_A1R5G5B5_UNORM        = TinyImageFormat_A1R5G5B5_UNORM,
	FT_FORMAT_B5G5B5X1_UNORM        = TinyImageFormat_R5G5B5X1_UNORM,
	FT_FORMAT_B5G5R5X1_UNORM        = TinyImageFormat_B5G5R5X1_UNORM,
	FT_FORMAT_X1R5G5B5_UNORM        = TinyImageFormat_X1R5G5B5_UNORM,
	FT_FORMAT_X1B5G5R5_UNORM        = TinyImageFormat_X1B5G5R5_UNORM,
	FT_FORMAT_B2G3R3A8_UNORM        = TinyImageFormat_B2G3R3A8_UNORM,
	FT_FORMAT_R8G8_UNORM            = TinyImageFormat_R8G8_UNORM,
	FT_FORMAT_R8G8_SNORM            = TinyImageFormat_R8G8_SNORM,
	FT_FORMAT_G8R8_UNORM            = TinyImageFormat_G8R8_UNORM,
	FT_FORMAT_G8R8_SNORM            = TinyImageFormat_G8R8_SNORM,
	FT_FORMAT_R8G8_UINT             = TinyImageFormat_R8G8_UINT,
	FT_FORMAT_R8G8_SINT             = TinyImageFormat_R8G8_SINT,
	FT_FORMAT_R8G8_SRGB             = TinyImageFormat_R8G8_SRGB,
	FT_FORMAT_R16_UNORM             = TinyImageFormat_R16_UNORM,
	FT_FORMAT_R16_SNORM             = TinyImageFormat_R16_SNORM,
	FT_FORMAT_R16_UINT              = TinyImageFormat_R16_UINT,
	FT_FORMAT_R16_SINT              = TinyImageFormat_R16_SINT,
	FT_FORMAT_R16_SFLOAT            = TinyImageFormat_R16_SFLOAT,
	FT_FORMAT_R16_SBFLOAT           = TinyImageFormat_R16_SBFLOAT,
	FT_FORMAT_R8G8B8_UNORM          = TinyImageFormat_R8G8B8_UNORM,
	FT_FORMAT_R8G8B8_SNORM          = TinyImageFormat_R8G8B8_SNORM,
	FT_FORMAT_R8G8B8_UINT           = TinyImageFormat_R8G8B8_UINT,
	FT_FORMAT_R8G8B8_SINT           = TinyImageFormat_R8G8B8_SINT,
	FT_FORMAT_R8G8B8_SRGB           = TinyImageFormat_R8G8B8_SRGB,
	FT_FORMAT_B8G8R8_UNORM          = TinyImageFormat_B8G8R8_UNORM,
	FT_FORMAT_B8G8R8_SNORM          = TinyImageFormat_B8G8R8_SNORM,
	FT_FORMAT_B8G8R8_UINT           = TinyImageFormat_B8G8R8_UINT,
	FT_FORMAT_B8G8R8_SINT           = TinyImageFormat_B8G8R8_SINT,
	FT_FORMAT_B8G8R8_SRGB           = TinyImageFormat_B8G8R8_SRGB,
	FT_FORMAT_R8G8B8A8_UNORM        = TinyImageFormat_R8G8B8A8_UNORM,
	FT_FORMAT_R8G8B8A8_SNORM        = TinyImageFormat_R8G8B8A8_SNORM,
	FT_FORMAT_R8G8B8A8_UINT         = TinyImageFormat_R8G8B8A8_UINT,
	FT_FORMAT_R8G8B8A8_SINT         = TinyImageFormat_R8G8B8A8_SINT,
	FT_FORMAT_R8G8B8A8_SRGB         = TinyImageFormat_R8G8B8A8_SRGB,
	FT_FORMAT_B8G8R8A8_UNORM        = TinyImageFormat_B8G8R8A8_UNORM,
	FT_FORMAT_B8G8R8A8_SNORM        = TinyImageFormat_B8G8R8A8_SNORM,
	FT_FORMAT_B8G8R8A8_UINT         = TinyImageFormat_B8G8R8A8_UINT,
	FT_FORMAT_B8G8R8A8_SINT         = TinyImageFormat_B8G8R8A8_SINT,
	FT_FORMAT_B8G8R8A8_SRGB         = TinyImageFormat_B8G8R8A8_SRGB,
	FT_FORMAT_R8G8B8X8_UNORM        = TinyImageFormat_R8G8B8X8_UNORM,
	FT_FORMAT_B8G8R8X8_UNORM        = TinyImageFormat_B8G8R8X8_UNORM,
	FT_FORMAT_R16G16_UNORM          = TinyImageFormat_R16G16_UNORM,
	FT_FORMAT_G16R16_UNORM          = TinyImageFormat_G16R16_UNORM,
	FT_FORMAT_R16G16_SNORM          = TinyImageFormat_R16G16_SNORM,
	FT_FORMAT_G16R16_SNORM          = TinyImageFormat_G16R16_SNORM,
	FT_FORMAT_R16G16_UINT           = TinyImageFormat_R16G16_UINT,
	FT_FORMAT_R16G16_SINT           = TinyImageFormat_R16G16_SINT,
	FT_FORMAT_R16G16_SFLOAT         = TinyImageFormat_R16G16_SFLOAT,
	FT_FORMAT_R16G16_SBFLOAT        = TinyImageFormat_R16G16_SBFLOAT,
	FT_FORMAT_R32_UINT              = TinyImageFormat_R32_UINT,
	FT_FORMAT_R32_SINT              = TinyImageFormat_R32_SINT,
	FT_FORMAT_R32_SFLOAT            = TinyImageFormat_R32_SFLOAT,
	FT_FORMAT_A2R10G10B10_UNORM     = TinyImageFormat_A2R10G10B10_UNORM,
	FT_FORMAT_A2R10G10B10_UINT      = TinyImageFormat_A2R10G10B10_UINT,
	FT_FORMAT_A2R10G10B10_SNORM     = TinyImageFormat_A2R10G10B10_SNORM,
	FT_FORMAT_A2R10G10B10_SINT      = TinyImageFormat_A2R10G10B10_SINT,
	FT_FORMAT_A2B10G10R10_UNORM     = TinyImageFormat_A2B10G10R10_UNORM,
	FT_FORMAT_A2B10G10R10_UINT      = TinyImageFormat_A2B10G10R10_UINT,
	FT_FORMAT_A2B10G10R10_SNORM     = TinyImageFormat_A2B10G10R10_SNORM,
	FT_FORMAT_A2B10G10R10_SINT      = TinyImageFormat_A2B10G10R10_SINT,
	FT_FORMAT_R10G10B10A2_UNORM     = TinyImageFormat_R10G10B10A2_UNORM,
	FT_FORMAT_R10G10B10A2_UINT      = TinyImageFormat_R10G10B10A2_UINT,
	FT_FORMAT_R10G10B10A2_SNORM     = TinyImageFormat_R10G10B10A2_SNORM,
	FT_FORMAT_R10G10B10A2_SINT      = TinyImageFormat_R10G10B10A2_SINT,
	FT_FORMAT_B10G10R10R10A2_UNORM  = TinyImageFormat_B10G10R10A2_UNORM,
	FT_FORMAT_B10G10R10R10A2_UINT   = TinyImageFormat_B10G10R10A2_UINT,
	FT_FORMAT_B10G10R10R10A2_SNORM  = TinyImageFormat_B10G10R10A2_SNORM,
	FT_FORMAT_B10G10R10R10A2_SINT   = TinyImageFormat_B10G10R10A2_SINT,
	FT_FORMAT_B10G10R11_UFLOAT      = TinyImageFormat_B10G11R11_UFLOAT,
	FT_FORMAT_E5B5G9R9_UFLOAT       = TinyImageFormat_E5B9G9R9_UFLOAT,
	FT_FORMAT_R16G16B16_UNORM       = TinyImageFormat_R16G16B16_UNORM,
	FT_FORMAT_R16G16B16_SNORM       = TinyImageFormat_R16G16B16_SNORM,
	FT_FORMAT_R16G16B16_UINT        = TinyImageFormat_R16G16B16_UINT,
	FT_FORMAT_R16G16B16_SINT        = TinyImageFormat_R16G16B16_SINT,
	FT_FORMAT_R16G16B16_SFLOAT      = TinyImageFormat_R16G16B16_SFLOAT,
	FT_FORMAT_R16G16B16_SBFLOAT     = TinyImageFormat_R16G16B16_SBFLOAT,
	FT_FORMAT_R16G16B16A16_UNORM    = TinyImageFormat_R16G16B16A16_UNORM,
	FT_FORMAT_R16G16B16A16_SNORM    = TinyImageFormat_R16G16B16A16_SNORM,
	FT_FORMAT_R16G16B16A16_UINT     = TinyImageFormat_R16G16B16A16_UINT,
	FT_FORMAT_R16G16B16A16_SINT     = TinyImageFormat_R16G16B16A16_SINT,
	FT_FORMAT_R16G16B16A16_SFLOAT   = TinyImageFormat_R16G16B16A16_SFLOAT,
	FT_FORMAT_R16G16B16A16_SBFLOAT  = TinyImageFormat_R16G16B16A16_SBFLOAT,
	FT_FORMAT_R32G32_UINT           = TinyImageFormat_R32G32_UINT,
	FT_FORMAT_R32G32_SINT           = TinyImageFormat_R32G32_SINT,
	FT_FORMAT_R32G32_SFLOAT         = TinyImageFormat_R32G32_SFLOAT,
	FT_FORMAT_R32G32B32_UINT        = TinyImageFormat_R32G32B32_UINT,
	FT_FORMAT_R32G32B32_SINT        = TinyImageFormat_R32G32B32_SINT,
	FT_FORMAT_R32G32B32_SFLOAT      = TinyImageFormat_R32G32B32_SFLOAT,
	FT_FORMAT_R32G32B32A32_UINT     = TinyImageFormat_R32G32B32A32_UINT,
	FT_FORMAT_R32G32B32A32_SINT     = TinyImageFormat_R32G32B32A32_SINT,
	FT_FORMAT_R32G32B32A32_SFLOAT   = TinyImageFormat_R32G32B32A32_SFLOAT,
	FT_FORMAT_R64_UINT              = TinyImageFormat_R64_UINT,
	FT_FORMAT_R64_SINT              = TinyImageFormat_R64_SINT,
	FT_FORMAT_R64_SFLOAT            = TinyImageFormat_R64_SFLOAT,
	FT_FORMAT_R64G64_UINT           = TinyImageFormat_R64G64_UINT,
	FT_FORMAT_R64G64_SINT           = TinyImageFormat_R64G64_SINT,
	FT_FORMAT_R64G64_SFLOAT         = TinyImageFormat_R64G64_SFLOAT,
	FT_FORMAT_R64G64B64_UINT        = TinyImageFormat_R64G64B64_UINT,
	FT_FORMAT_R64G64B64_SINT        = TinyImageFormat_R64G64B64_SINT,
	FT_FORMAT_R64G64B64_SFLOAT      = TinyImageFormat_R64G64B64_SFLOAT,
	FT_FORMAT_R64G64B64A64_UINT     = TinyImageFormat_R64G64B64A64_UINT,
	FT_FORMAT_R64G64B64A64_SINT     = TinyImageFormat_R64G64B64A64_SINT,
	FT_FORMAT_R64G64B64A64_SFLOAT   = TinyImageFormat_R64G64B64A64_SFLOAT,
	FT_FORMAT_D16_UNORM             = TinyImageFormat_D16_UNORM,
	FT_FORMAT_X8D24_UNORM           = TinyImageFormat_X8_D24_UNORM,
	FT_FORMAT_D32_SFLOAT            = TinyImageFormat_D32_SFLOAT,
	FT_FORMAT_S8_UINT               = TinyImageFormat_S8_UINT,
	FT_FORMAT_D16_UNORMS8_UINT      = TinyImageFormat_D16_UNORM_S8_UINT,
	FT_FORMAT_D24_UNORMS8_UINT      = TinyImageFormat_D24_UNORM_S8_UINT,
	FT_FORMAT_D32_SFLOATS8_UINT     = TinyImageFormat_D32_SFLOAT_S8_UINT,
	FT_FORMAT_DXBC1_RGB_UNORM       = TinyImageFormat_DXBC1_RGB_UNORM,
	FT_FORMAT_DXBC1_RGB_SRGB        = TinyImageFormat_DXBC1_RGB_SRGB,
	FT_FORMAT_DXBC1_RGBA_UNORM      = TinyImageFormat_DXBC1_RGBA_UNORM,
	FT_FORMAT_DXBC1_RGBA_SRGB       = TinyImageFormat_DXBC1_RGBA_SRGB,
	FT_FORMAT_DXBC2_UNORM           = TinyImageFormat_DXBC2_UNORM,
	FT_FORMAT_DXBC2_SRGB            = TinyImageFormat_DXBC2_SRGB,
	FT_FORMAT_DXBC3_UNORM           = TinyImageFormat_DXBC3_UNORM,
	FT_FORMAT_DXBC3_SRGB            = TinyImageFormat_DXBC3_SRGB,
	FT_FORMAT_DXBC4_UNORM           = TinyImageFormat_DXBC4_UNORM,
	FT_FORMAT_DXBC4_SNORM           = TinyImageFormat_DXBC4_SNORM,
	FT_FORMAT_DXBC5_UNORM           = TinyImageFormat_DXBC5_UNORM,
	FT_FORMAT_DXBC5_SNORM           = TinyImageFormat_DXBC5_SNORM,
	FT_FORMAT_DXBC6H_UFLOAT         = TinyImageFormat_DXBC6H_UFLOAT,
	FT_FORMAT_DXBC6H_SFLOAT         = TinyImageFormat_DXBC6H_SFLOAT,
	FT_FORMAT_DXBC7_UNORM           = TinyImageFormat_DXBC7_UNORM,
	FT_FORMAT_DXBC7_SRGB            = TinyImageFormat_DXBC7_SRGB,
	FT_FORMAT_PVRTC1_2BPP_UNORM     = TinyImageFormat_PVRTC1_2BPP_UNORM,
	FT_FORMAT_PVRTC1_4BPP_UNORM     = TinyImageFormat_PVRTC1_4BPP_UNORM,
	FT_FORMAT_PVRTC2_2BPP_UNORM     = TinyImageFormat_PVRTC2_2BPP_UNORM,
	FT_FORMAT_PVRTC2_4BPP_UNORM     = TinyImageFormat_PVRTC2_4BPP_UNORM,
	FT_FORMAT_PVRTC1_2BPP_SRGB      = TinyImageFormat_PVRTC1_2BPP_SRGB,
	FT_FORMAT_PVRTC1_4BPP_SRGB      = TinyImageFormat_PVRTC1_4BPP_SRGB,
	FT_FORMAT_PVRTC2_2BPP_SRGB      = TinyImageFormat_PVRTC2_2BPP_SRGB,
	FT_FORMAT_PVRTC2_4BPP_SRGB      = TinyImageFormat_PVRTC2_4BPP_SRGB,
	FT_FORMAT_ETC2_R8G8B8_UNORM     = TinyImageFormat_ETC2_R8G8B8_UNORM,
	FT_FORMAT_ETC2_R8G8B8_SRGB      = TinyImageFormat_ETC2_R8G8B8_SRGB,
	FT_FORMAT_ETC2_R8G8B8A1_UNORM   = TinyImageFormat_ETC2_R8G8B8A1_UNORM,
	FT_FORMAT_ETC2_R8G8B8A1_SRGB    = TinyImageFormat_ETC2_R8G8B8A1_SRGB,
	FT_FORMAT_ETC2_R8G8B8A8_UNORM   = TinyImageFormat_ETC2_R8G8B8A8_UNORM,
	FT_FORMAT_ETC2_R8G8B8A8_SRGB    = TinyImageFormat_ETC2_R8G8B8A8_SRGB,
	FT_FORMAT_ETC2_EAC_R11_UNORM    = TinyImageFormat_ETC2_EAC_R11_UNORM,
	FT_FORMAT_ETC2_EAC_R11_SNORM    = TinyImageFormat_ETC2_EAC_R11_SNORM,
	FT_FORMAT_ETC2_EAC_R11G11_UNORM = TinyImageFormat_ETC2_EAC_R11G11_UNORM,
	FT_FORMAT_ETC2_EAC_R11G11_SNORM = TinyImageFormat_ETC2_EAC_R11G11_SNORM,
	FT_FORMAT_ASTC_4x4_UNORM        = TinyImageFormat_ASTC_4x4_UNORM,
	FT_FORMAT_ASTC_4x4_SRGB         = TinyImageFormat_ASTC_4x4_SRGB,
	FT_FORMAT_ASTC_5x4_UNORM        = TinyImageFormat_ASTC_5x4_UNORM,
	FT_FORMAT_ASTC_5x4_SRGB         = TinyImageFormat_ASTC_5x4_SRGB,
	FT_FORMAT_ASTC_5x5_UNORM        = TinyImageFormat_ASTC_5x5_UNORM,
	FT_FORMAT_ASTC_5x5_SRGB         = TinyImageFormat_ASTC_5x5_SRGB,
	FT_FORMAT_ASTC_6x5_UNORM        = TinyImageFormat_ASTC_6x5_UNORM,
	FT_FORMAT_ASTC_6x5_SRGB         = TinyImageFormat_ASTC_6x5_SRGB,
	FT_FORMAT_ASTC_6x6_UNORM        = TinyImageFormat_ASTC_6x6_UNORM,
	FT_FORMAT_ASTC_6x6_SRGB         = TinyImageFormat_ASTC_6x6_SRGB,
	FT_FORMAT_ASTC_8x5_UNORM        = TinyImageFormat_ASTC_8x5_UNORM,
	FT_FORMAT_ASTC_8x5_SRGB         = TinyImageFormat_ASTC_8x5_SRGB,
	FT_FORMAT_ASTC_8x6_UNORM        = TinyImageFormat_ASTC_8x6_UNORM,
	FT_FORMAT_ASTC_8x6_SRGB         = TinyImageFormat_ASTC_8x6_SRGB,
	FT_FORMAT_ASTC_8x8_UNORM        = TinyImageFormat_ASTC_8x8_UNORM,
	FT_FORMAT_ASTC_8x8_SRGB         = TinyImageFormat_ASTC_8x8_SRGB,
	FT_FORMAT_ASTC_10x5_UNORM       = TinyImageFormat_ASTC_10x5_UNORM,
	FT_FORMAT_ASTC_10x5_SRGB        = TinyImageFormat_ASTC_10x5_SRGB,
	FT_FORMAT_ASTC_10x6_UNORM       = TinyImageFormat_ASTC_10x6_UNORM,
	FT_FORMAT_ASTC_10x6_SRGB        = TinyImageFormat_ASTC_10x6_SRGB,
	FT_FORMAT_ASTC_10x8_UNORM       = TinyImageFormat_ASTC_10x8_UNORM,
	FT_FORMAT_ASTC_10x8_SRGB        = TinyImageFormat_ASTC_10x8_SRGB,
	FT_FORMAT_ASTC_10x10_UNORM      = TinyImageFormat_ASTC_10x10_UNORM,
	FT_FORMAT_ASTC_10x10_SRGB       = TinyImageFormat_ASTC_10x10_SRGB,
	FT_FORMAT_ASTC_12x10_UNORM      = TinyImageFormat_ASTC_12x10_UNORM,
	FT_FORMAT_ASTC_12x10_SRGB       = TinyImageFormat_ASTC_12x10_SRGB,
	FT_FORMAT_ASTC_12x12_UNORM      = TinyImageFormat_ASTC_12x12_UNORM,
	FT_FORMAT_ASTC_12x12_SRGB       = TinyImageFormat_ASTC_12x12_SRGB,
	FT_FORMAT_CLUT_P4               = TinyImageFormat_CLUT_P4,
	FT_FORMAT_CLUT_P4A4             = TinyImageFormat_CLUT_P4A4,
	FT_FORMAT_CLUT_P8               = TinyImageFormat_CLUT_P8,
	FT_FORMAT_CLUT_P8A8             = TinyImageFormat_CLUT_P8A8,
} Format;

typedef enum AttachmentLoadOp
{
	FT_ATTACHMENT_LOAD_OP_LOAD,
	FT_ATTACHMENT_LOAD_OP_CLEAR     = 1,
	FT_ATTACHMENT_LOAD_OP_DONT_CARE = 2
} AttachmentLoadOp;

typedef enum MemoryUsage
{
	FT_MEMORY_USAGE_GPU_ONLY   = 0,
	FT_MEMORY_USAGE_CPU_ONLY   = 1,
	FT_MEMORY_USAGE_CPU_TO_GPU = 2,
	FT_MEMORY_USAGE_GPU_TO_CPU = 3,
	FT_MEMORY_USAGE_CPU_COPY   = 4,
} MemoryUsage;

typedef enum ResourceState
{
	FT_RESOURCE_STATE_UNDEFINED               = BIT( 0 ),
	FT_RESOURCE_STATE_GENERAL                 = BIT( 1 ),
	FT_RESOURCE_STATE_COLOR_ATTACHMENT        = BIT( 2 ),
	FT_RESOURCE_STATE_DEPTH_STENCIL_WRITE     = BIT( 3 ),
	FT_RESOURCE_STATE_DEPTH_STENCIL_READ_ONLY = BIT( 4 ),
	FT_RESOURCE_STATE_SHADER_READ_ONLY        = BIT( 5 ),
	FT_RESOURCE_STATE_TRANSFER_SRC            = BIT( 6 ),
	FT_RESOURCE_STATE_TRANSFER_DST            = BIT( 7 ),
	FT_RESOURCE_STATE_PRESENT                 = BIT( 8 )
} ResourceState;

typedef enum DescriptorType
{
	FT_DESCRIPTOR_TYPE_UNDEFINED                = BIT( 0 ),
	FT_DESCRIPTOR_TYPE_VERTEX_BUFFER            = BIT( 1 ),
	FT_DESCRIPTOR_TYPE_INDEX_BUFFER             = BIT( 2 ),
	FT_DESCRIPTOR_TYPE_UNIFORM_BUFFER           = BIT( 3 ),
	FT_DESCRIPTOR_TYPE_SAMPLER                  = BIT( 4 ),
	FT_DESCRIPTOR_TYPE_SAMPLED_IMAGE            = BIT( 5 ),
	FT_DESCRIPTOR_TYPE_STORAGE_IMAGE            = BIT( 6 ),
	FT_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER     = BIT( 7 ),
	FT_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER     = BIT( 8 ),
	FT_DESCRIPTOR_TYPE_STORAGE_BUFFER           = BIT( 9 ),
	FT_DESCRIPTOR_TYPE_INDIRECT_BUFFER          = BIT( 10 ),
	FT_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC   = BIT( 11 ),
	FT_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC   = BIT( 12 ),
	FT_DESCRIPTOR_TYPE_INPUT_ATTACHMENT         = BIT( 13 ),
	FT_DESCRIPTOR_TYPE_DEPTH_STENCIL_ATTACHMENT = BIT( 14 ),
	FT_DESCRIPTOR_TYPE_COLOR_ATTACHMENT         = BIT( 15 ),
	FT_DESCRIPTOR_TYPE_TRANSIENT_ATTACHMENT     = BIT( 16 )
} DescriptorType;

typedef enum PipelineType
{
	FT_PIPELINE_TYPE_COMPUTE,
	FT_PIPELINE_TYPE_GRAPHICS
} PipelineType;

typedef enum VertexInputRate
{
	FT_VERTEX_INPUT_RATE_VERTEX,
	FT_VERTEX_INPUT_RATE_INSTANCE
} VertexInputRate;

typedef enum FrontFace
{
	FT_FRONT_FACE_CLOCKWISE,
	FT_FRONT_FACE_COUNTER_CLOCKWISE
} FrontFace;

typedef enum PolygonMode
{
	FT_POLYGON_MODE_FILL,
	FT_POLYGON_MODE_LINE
} PolygonMode;

typedef enum SamplerMipmapMode
{
	FT_SAMPLER_MIPMAP_MODE_NEAREST,
	FT_SAMPLER_MIPMAP_MODE_LINEAR
} SamplerMipmapMode;

typedef enum SamplerAddressMode
{
	FT_SAMPLER_ADDRESS_MODE_REPEAT,
	FT_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT,
	FT_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
	FT_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER
} SamplerAddressMode;

typedef enum CompareOp
{
	FT_COMPARE_OP_NEVER,
	FT_COMPARE_OP_LESS,
	FT_COMPARE_OP_EQUAL,
	FT_COMPARE_OP_LESS_OR_EQUAL,
	FT_COMPARE_OP_GREATER,
	FT_COMPARE_OP_NOT_EQUAL,
	FT_COMPARE_OP_GREATER_OR_EQUAL,
	FT_COMPARE_OP_ALWAYS
} CompareOp;

typedef enum CullMode
{
	FT_CULL_MODE_NONE,
	FT_CULL_MODE_FRONT,
	FT_CULL_MODE_BACK
} CullMode;

typedef enum ShaderStage
{
	FT_SHADER_STAGE_VERTEX,
	FT_SHADER_STAGE_TESSELLATION_CONTROL,
	FT_SHADER_STAGE_TESSELLATION_EVALUATION,
	FT_SHADER_STAGE_GEOMETRY,
	FT_SHADER_STAGE_FRAGMENT,
	FT_SHADER_STAGE_COMPUTE,
	FT_SHADER_STAGE_COUNT
} ShaderStage;

typedef enum Filter
{
	FT_FILTER_NEAREST = 0,
	FT_FILTER_LINEAR  = 1,
} Filter;

typedef enum PrimitiveTopology
{
	FT_PRIMITIVE_TOPOLOGY_POINT_LIST,
	FT_PRIMITIVE_TOPOLOGY_LINE_LIST,
	FT_PRIMITIVE_TOPOLOGY_LINE_STRIP,
	FT_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
	FT_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP
} PrimitiveTopology;
